# Generated by Django 3.1.7 on 2021-03-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_puplished',
            new_name='is_published',
        ),
    ]
